name: PowerShell Pester Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PowerShell
      uses: actions/setup-powershell@v2

    - name: Install Pester
      run: |
        Install-Module -Name Pester -Force -Scope CurrentUser
        Import-Module Pester

    - name: Run Pester Tests
      run: |
        Invoke-Pester -Script "./Tests" -Output Detailed -ErrorAction Stop
